[[GTKmm3]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7ddb184527d194c6ad212f7dfe799e0aae47c77"
os = "macos"

    [[GTKmm3.download]]
    sha256 = "fbc136d4db6f1ba6ebd6482e58f2a076ea759074e75354a4006070ab5d171f90"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.aarch64-apple-darwin-cxx03.tar.gz"
[[GTKmm3]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d029659288fe499c020d90ba6fd2454a220bb3f"
os = "macos"

    [[GTKmm3.download]]
    sha256 = "6bc65329df3cbd1baee48f986ddaa7487dea00c250494e7c9e4ab9a347efcf11"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.aarch64-apple-darwin-cxx11.tar.gz"
[[GTKmm3]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae25012fe42ff0ca523d6bec399229f7a8142808"
libc = "glibc"
os = "linux"

    [[GTKmm3.download]]
    sha256 = "16efeded3185d5d3748ba20383228336afb7b47e82226546d908cca834e7f3a0"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.aarch64-linux-gnu-cxx03.tar.gz"
[[GTKmm3]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb5f7c50ee61c05aa4db3d6967e8183dc98bb7f4"
libc = "glibc"
os = "linux"

    [[GTKmm3.download]]
    sha256 = "8ebb2298ead345dd88abeae4d5700fe084832a743017f389f91121b874d0b651"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.aarch64-linux-gnu-cxx11.tar.gz"
[[GTKmm3]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f0787f311547d3b8b59707f43e52f6ed4028c30"
libc = "musl"
os = "linux"

    [[GTKmm3.download]]
    sha256 = "712ac55416d19c0a74979e1d21c0d21c347725ce223f20d3cea950fc8d9628c0"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.aarch64-linux-musl-cxx03.tar.gz"
[[GTKmm3]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b467be1c22dd477c02830f3b130807272ad91a5e"
libc = "musl"
os = "linux"

    [[GTKmm3.download]]
    sha256 = "1a30227ca0a6c527301c309ad70a8f6d712064cf4a21788d3efc978f75babe73"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.aarch64-linux-musl-cxx11.tar.gz"
[[GTKmm3]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "977fe6082f410bf0d7de6ece6c088708df718e23"
libc = "glibc"
os = "linux"

    [[GTKmm3.download]]
    sha256 = "1f239a3c60468f2519422cd604baf4b14fa64a850a495f5461b2038adb90e9dd"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[GTKmm3]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "65a51e6701841f73fd238b4615746d4b31a9d7fa"
libc = "glibc"
os = "linux"

    [[GTKmm3.download]]
    sha256 = "e65daf832fcbf2ed86271fb2266801e0ff6d0d3cc3c5e26d21f8640244bf9958"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GTKmm3]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7193fc57b6a75e88dba34ca125581a1b3d575b8d"
libc = "musl"
os = "linux"

    [[GTKmm3.download]]
    sha256 = "db516e1f4dbf110338c310951d4ea1cb140aeecacd682785d540fc97680b3e41"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.armv7l-linux-musleabihf-cxx03.tar.gz"
[[GTKmm3]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a116386bbfae4cb1252b4aab8cd066c16d31a71b"
libc = "musl"
os = "linux"

    [[GTKmm3.download]]
    sha256 = "3b9a5a1ae8ecf83a9e08a799108fccb325445414db1b89ca008c820a22ae944c"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GTKmm3]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2341a445df6fd46fdb69a94cd9674a17901ad19f"
libc = "glibc"
os = "linux"

    [[GTKmm3.download]]
    sha256 = "d381e91a0b85eed454632617379e80095a8710a862fde91eb106e7a5dadddab8"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.i686-linux-gnu-cxx03.tar.gz"
[[GTKmm3]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fc7ae579fb8e04daf7c053fc56de83808b97311a"
libc = "glibc"
os = "linux"

    [[GTKmm3.download]]
    sha256 = "f7c3718cb9f19330257f442ba26fc197c35106b64fb95bf9f2bcf30a8862d41a"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.i686-linux-gnu-cxx11.tar.gz"
[[GTKmm3]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c3a600151c66bab5ee5b2364c38e027b8fddca9"
libc = "musl"
os = "linux"

    [[GTKmm3.download]]
    sha256 = "24b5e87013376fde992682ad80fc25ff0911eece76abae897f44876c648e9cd9"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.i686-linux-musl-cxx03.tar.gz"
[[GTKmm3]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ce1076f4ad4f64c0fc99bf1e44dc8f8b439ceb2"
libc = "musl"
os = "linux"

    [[GTKmm3.download]]
    sha256 = "f1c9414a0fb1fac203067a5ccb1071cfedb81eb09485d48fa7a7012c7e25b1e7"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.i686-linux-musl-cxx11.tar.gz"
[[GTKmm3]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c7e23ff97dd6f973963d133a2e5648dda266c40a"
os = "windows"

    [[GTKmm3.download]]
    sha256 = "3fc7abbeeb61c4c6feff21083aad97f36d32d348b16845a2fd9e4d200a9dbc4f"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.i686-w64-mingw32-cxx03.tar.gz"
[[GTKmm3]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1876363077e5085fd5080c9500805e4a8f33b542"
os = "windows"

    [[GTKmm3.download]]
    sha256 = "a185e1d369123d56e75cc48b1d7095d3e3b1eccb489e8c2805d09aaee98c4ea7"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.i686-w64-mingw32-cxx11.tar.gz"
[[GTKmm3]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c5f002c94b2134b4067a02c1c1bb9fcf68fb0ec"
libc = "glibc"
os = "linux"

    [[GTKmm3.download]]
    sha256 = "b1aaa84ddc719e3aa7d8d273bfa9a89b916ecd75320ced4bcbf2a42a095493c6"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[GTKmm3]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f7a777ff9ba346dc3375fdd7e22c263d756a88b"
libc = "glibc"
os = "linux"

    [[GTKmm3.download]]
    sha256 = "6fb8541ab28c6a558c65482283baec8699db679f0457bd5af813d8f9b710da39"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GTKmm3]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3120da10b3ba3716310e530268f1cb9babe73966"
os = "macos"

    [[GTKmm3.download]]
    sha256 = "fe5dc065ae676af36a7e829f2234a71077532dc088792b002271372dd422ffc9"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.x86_64-apple-darwin-cxx03.tar.gz"
[[GTKmm3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f380d6438b2434726734709b4c642dd3def6f896"
os = "macos"

    [[GTKmm3.download]]
    sha256 = "6e80a7d0be637e2ba8f303b5443b78defdb2781371e7f54dc9dece1791c07909"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.x86_64-apple-darwin-cxx11.tar.gz"
[[GTKmm3]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99f1ec4bb1f40dc91edd83d6b243e8f1a87e0520"
libc = "glibc"
os = "linux"

    [[GTKmm3.download]]
    sha256 = "1dd7f8e07eae8c87d57476a23299b960ec02e4276a813c195338ee398d63251d"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.x86_64-linux-gnu-cxx03.tar.gz"
[[GTKmm3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a764693a2ada8434d8227866f524e4e1f1170aa1"
libc = "glibc"
os = "linux"

    [[GTKmm3.download]]
    sha256 = "8f09f5f365fbe3bcab3624d47c1fc10d428cd60e78b42fdc1b7a7e507272c0a9"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.x86_64-linux-gnu-cxx11.tar.gz"
[[GTKmm3]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b688773f9698254a4d210632576455a04429d740"
libc = "musl"
os = "linux"

    [[GTKmm3.download]]
    sha256 = "5128efdfbab9bb42ddacda0d9c934c495df024b5c516cf2d10213b6503d28be8"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.x86_64-linux-musl-cxx03.tar.gz"
[[GTKmm3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06f172c0038f76336e7f16312a10995ce779e56b"
libc = "musl"
os = "linux"

    [[GTKmm3.download]]
    sha256 = "58701034342c256a77f1218ddb6d33a421adfbea39c9fe046015947236fa6c41"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.x86_64-linux-musl-cxx11.tar.gz"
[[GTKmm3]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3ed1873e106ff2a44611ce11a23db53dd4bef3da"
os = "freebsd"

    [[GTKmm3.download]]
    sha256 = "890fe45ef255c8fbe498d6197eabc3810bafbf9b310f2dcd72b7911fc29f1673"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.x86_64-unknown-freebsd-cxx03.tar.gz"
[[GTKmm3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2af1b655c85abc795d9b8012169844e482dd71c"
os = "freebsd"

    [[GTKmm3.download]]
    sha256 = "1c8d2032f797c6cfc5bd1b4c61540f06357449afb9eb7e0152f0d7f427e4af6b"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.x86_64-unknown-freebsd-cxx11.tar.gz"
[[GTKmm3]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d8945c4fce0688c7ab05d730dc224a8d442f7734"
os = "windows"

    [[GTKmm3.download]]
    sha256 = "f2dac790accca3ca30ca44986642565e753ea628166c1787f2816525717904c2"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[GTKmm3]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "652bd5f85714adfd955b8424fa3ad56205709154"
os = "windows"

    [[GTKmm3.download]]
    sha256 = "185481af7f95a5f8655ad68cb7e27285911a8a2af52958790c8c8d8df82c019e"
    url = "https://github.com/JuliaBinaryWrappers/GTKmm3_jll.jl/releases/download/GTKmm3-v3.24.7+1/GTKmm3.v3.24.7.x86_64-w64-mingw32-cxx11.tar.gz"
